version: '{branch}-{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform:
- x86
- x64

for:
#x86
-
  matrix:
    only:
      - platform: x86

  environment:
      QTDIR: C:\Qt\5.12.5\msvc2017

#x64
-
  matrix:
    only:
    - platform: x64

  environment:
      QTDIR: C:\Qt\5.12.5\msvc2017_64

build_script:
  - cmd: msbuild "C:\projects\gcadapter64\gcadapter64.sln" /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:QtInstall=%QTDIR%
after_build:
- ps: .\deploy\pj64package.ps1 -platform "$($env:PLATFORM)"
