version: '{branch}-{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - platform: x86
    QtInstallDir: C:\Qt\5.12.4\msvc2017

  - platform: x64
    QtInstallDir: C:\Qt\5.12.4\msvc2017_64

build:
  project: gcadapter64.sln
  parallel: true
  verbosity: detailed
after_build:
- ps: .\deploy\pj64package.ps1 -platform "$($env:PLATFORM)"
