version: '{branch}-{build}'
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform:
- x86
- x64

for:
#x86
-
  matrix:
    only:
      - platform: x86

  environment:
      QTDIR: C:\Qt\5.12.5\msvc2017

#x64
-
  matrix:
    only:
    - platform: x64

  environment:
      QTDIR: C:\Qt\5.12.5\msvc2017_64

build:
  project: gcadapter64.sln
  parallel: true
  verbosity: normal
after_build:
- ps: .\deploy\pj64package.ps1 -platform "$($env:PLATFORM)"
