# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = gcadapter64
DESTDIR = ./build/Win32/Debug
CONFIG += debug
DEFINES += GCADAPTER64_LIB
LIBS += -llibusb-1.0
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(gcadapter64.pri)
